# Generated by Django 4.1 on 2023-12-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=30)),
                ('precoVenda', models.DecimalField(decimal_places=3, max_digits=15)),
                ('precoExpotacao', models.DecimalField(decimal_places=3, max_digits=15)),
                ('precoNacional', models.DecimalField(decimal_places=3, max_digits=15)),
                ('ret', models.CharField(choices=[('R', 'R'), ('N', 'N'), ('D', 'D')], default='R', max_length=1)),
                ('cc', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=3, max_digits=15)),
                ('comprimento', models.DecimalField(decimal_places=3, max_digits=15)),
                ('largura', models.DecimalField(decimal_places=3, max_digits=15)),
                ('altura', models.DecimalField(decimal_places=3, max_digits=15)),
                ('ncm', models.IntegerField()),
                ('gde', models.IntegerField()),
            ],
        ),
    ]
