# Generated by Django 3.1.5 on 2023-12-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=50)),
                ('cpfCnpj', models.CharField(max_length=14)),
                ('rgIE', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=20)),
                ('telfone', models.CharField(max_length=20)),
                ('contato', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('dataEmissao', models.DateField()),
                ('dataValidade', models.DateField()),
                ('tipoEntrega', models.CharField(choices=[('3', 'Transportadora')], default='3', max_length=1)),
                ('responsavel', models.CharField(max_length=50)),
                ('frete', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='peca',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPedido', models.IntegerField()),
                ('codigoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.cliente')),
                ('codigoOrcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.orcamento')),
                ('codigoPeca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.peca')),
            ],
        ),
    ]
