# Generated by Django 4.1 on 2024-02-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_pedido_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='dataEntrega',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
