# Generated by Django 4.1 on 2024-02-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_pedido_dataentrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='estado',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telfone',
            new_name='telefone',
        ),
    ]
