# Generated by Django 4.1 on 2024-11-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_alter_pedido_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
