# Generated by Django 4.1 on 2024-03-18 15:57

from django.db import migrations, models
import django.db.models.deletion
import loja.models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_rename_estado_cliente_pais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPessoa', models.CharField(choices=[('f', 'Pessoa Fisica'), ('j', 'Pessoa Juridica')], default='j', max_length=1)),
                ('nomeFornecedor', models.CharField(max_length=50)),
                ('cpfCnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=60)),
                ('pais', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('detalhe', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='contato',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rgIE',
        ),
        migrations.AddField(
            model_name='cliente',
            name='detalhe',
            field=models.TextField(default='detalhe: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoPessoa',
            field=models.CharField(choices=[('f', 'Pessoa Fisica'), ('j', 'Pessoa Juridica')], default='j', max_length=1),
        ),
        migrations.AddField(
            model_name='peca',
            name='codigoInterno',
            field=models.IntegerField(default=loja.models.add_ten),
        ),
        migrations.AddField(
            model_name='peca',
            name='marca',
            field=models.CharField(default='John Deere', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigoCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigoOrcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.orcamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigoPeca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.peca'),
        ),
        migrations.CreateModel(
            name='PecaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('fonecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.fornecedor')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.peca')),
            ],
        ),
    ]
