# Generated by Django 4.1 on 2024-11-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_pedido_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
