# Generated by Django 4.1 on 2024-03-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_fornecedor_rename_contato_cliente_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecafornecedor',
            name='preco',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
