# Generated by Django 4.1 on 2024-03-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_alter_orcamento_frete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('codigoPecaFornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.pecafornecedor')),
                ('codigoPedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.pedido')),
            ],
        ),
    ]
