# Generated by Django 4.1 on 2024-04-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_cotacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('empresa', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=30)),
                ('site', models.URLField()),
                ('cpfCnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=60)),
                ('pais', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='orcamento',
            name='cidadeEntrega',
            field=models.CharField(default='ribeiraõ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='cnpjEntrega',
            field=models.CharField(default='123', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='enderecoEntrega',
            field=models.CharField(default='tamioios, 262', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='marcasEmbarque',
            field=models.CharField(default='AGRIMIX // BRASIL // AZUCARERA PARAGUAYA S.A. // PARAGUAY', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='nomeEntrega',
            field=models.CharField(default='jao', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='paisEntrega',
            field=models.CharField(default='brasil', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='pacote',
            field=models.CharField(default='caixa de madeira', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='pesoBruto',
            field=models.DecimalField(decimal_places=3, default=20, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='unidade',
            field=models.CharField(default='unit', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='volume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='volumeBruto',
            field=models.DecimalField(decimal_places=3, default=20, max_digits=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CondicaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Não Pago'), ('2', 'Pago')], default='1', max_length=1)),
                ('cota', models.CharField(max_length=255)),
                ('porcentagem', models.DecimalField(decimal_places=3, max_digits=15)),
                ('data', models.DateField()),
                ('total', models.DecimalField(decimal_places=3, max_digits=15)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.orcamento')),
            ],
        ),
    ]
