# Generated by Django 4.1 on 2024-04-09 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_notificar_orcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=255)),
                ('cpfCnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=60)),
                ('pais', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('detalhe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEmicao', models.DateField(auto_now_add=True)),
                ('operacaoFiscal', models.CharField(max_length=255)),
                ('vencimento', models.CharField(choices=[('1', '28'), ('2', '30'), ('3', '30/60/90'), ('4', '28/56/84'), ('5', '30/60'), ('6', '28/56'), ('7', '30/45/60')], max_length=50)),
                ('comprador', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('observacoes', models.TextField()),
                ('frete', models.CharField(max_length=255)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.cotacao')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.transportadora')),
            ],
        ),
    ]
