# Generated by Django 4.1 on 2024-04-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_transportadora_pedidocompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportadora',
            name='cpfCnpj',
        ),
    ]
