# Generated by Django 4.1 on 2024-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='site',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='site',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='site',
            field=models.CharField(max_length=200),
        ),
    ]
