# Generated by Django 4.1 on 2024-04-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_alter_cliente_site_alter_fornecedor_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pecafornecedor',
            old_name='fonecedor',
            new_name='fornecedor',
        ),
    ]
