# Generated by Django 4.1 on 2024-06-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_rename_fonecedor_pecafornecedor_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('pacote', models.CharField(max_length=255)),
                ('comprimento', models.DecimalField(decimal_places=3, max_digits=15)),
                ('largura', models.DecimalField(decimal_places=3, max_digits=15)),
                ('altura', models.DecimalField(decimal_places=3, max_digits=15)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=15)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.orcamento')),
            ],
        ),
    ]
