# Generated by Django 4.1 on 2024-08-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0023_alter_usuario_cep_alter_usuario_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nomeCliente',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='site',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=250),
        ),
    ]
