# Generated by Django 4.1 on 2024-09-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0024_alter_cliente_cep_alter_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='estado',
            field=models.CharField(choices=[('1', 'fora de estoque'), ('2', 'em estoque'), ('3', 'entregue ao cliente')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
