# Generated by Django 4.1 on 2024-09-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0026_alter_pedidocompra_cotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='codigoPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.pedido'),
        ),
    ]
