# Generated by Django 4.1 on 2024-09-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0027_alter_estoque_codigopedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='codigoPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.pedido'),
        ),
    ]
