# Generated by Django 4.1 on 2024-09-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0028_alter_cotacao_codigopedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocompra',
            name='cotacao',
        ),
        migrations.AddField(
            model_name='cotacao',
            name='PedidoCompra',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='loja.pedidocompra'),
            preserve_default=False,
        ),
    ]
