# Generated by Django 4.1 on 2024-09-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0030_pedidocompra_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotacao',
            name='PedidoCompra',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='codigo',
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='orcamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='loja.orcamento'),
            preserve_default=False,
        ),
    ]
