# Generated by Django 4.1 on 2024-09-26 14:47

from django.db import migrations, models
import django.db.models.deletion
import loja.models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0031_remove_cotacao_pedidocompra_remove_cotacao_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.IntegerField(default=loja.models.add_dez),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='tipoEntrega',
            field=models.CharField(choices=[('1', 'EXW'), ('2', 'FCA'), ('3', 'FAS'), ('4', 'FOB'), ('5', 'CIF'), ('6', 'CFR'), ('7', 'CTP'), ('8', 'CIP'), ('9', 'DAT'), ('10', 'DAP'), ('11', 'DDP')], default='3', max_length=5),
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.IntegerField()),
                ('dataEmissao', models.DateField()),
                ('PedidoCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.pedidocompra')),
            ],
        ),
    ]
