# Generated by Django 4.1 on 2024-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0032_alter_orcamento_codigo_alter_orcamento_tipoentrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecafornecedor',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
