
#Para servidor Linux
services:

  djangoapp:
    image: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
