services:

  django-web:
    build: .
    container_name: django-docker
    volumes:
      - ./static:/app/staticfiles
    ports:
      - 80:80
    env_file:
      - .env.local

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - django-web