services:

  django-web:
    build: .
    container_name: django-docker
    volumes:
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - ALLOWED_HOSTS=127.0.0.1,localhost,0.0.0.0
      - PYTHONPATH=/app
    env_file:
      - .env.local
    restart: unless-stopped

  # Uncomment below for nginx reverse proxy
  # frontend-proxy:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./data/web/static:/static:ro
  #   depends_on:
  #     - django-web
  #   restart: unless-stopped