# Generated by Django 4.1 on 2024-10-23 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rename_nomecliente_cliente_nome_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocompra',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
