# Generated by Django 4.1 on 2024-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_pedido_desconto_pedido_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descricao',
            field=models.CharField(default='', max_length=255),
        ),
    ]
