# Generated by Django 4.1 on 2024-02-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizada', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('tecnica', models.IntegerField(choices=[(0, 'Multipla Escolha')], default=0, verbose_name='Tipo de Pergunta')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('opcao', models.IntegerField(choices=[(1, 'Muito Pouco'), (2, 'Pouco'), (3, 'Razoavel'), (4, 'Ok'), (5, 'Muito')], default=3, verbose_name='Opção')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('esta_ativo', models.BooleanField(default=True, verbose_name='Status de Ativação')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizada', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('resposta_texto', models.CharField(max_length=255, verbose_name='Resposta Texto')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resposta', to='diagnostico.pergunta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Novo Questionário', max_length=255, verbose_name='Título do Questionário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostico.categoria')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pergunta', to='diagnostico.questionario'),
        ),
    ]
