# Generated by Django 4.1 on 2024-02-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionario',
            options={},
        ),
    ]
