# Generated by Django 4.1 on 2024-02-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_alter_questionario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionario',
            options={'ordering': ['id'], 'verbose_name': 'Questionário', 'verbose_name_plural': 'Questionários'},
        ),
    ]
